// <auto-generated />
namespace RateItData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingOnModelCreatingTrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingOnModelCreatingTrue));
        
        string IMigrationMetadata.Id
        {
            get { return "202006031811449_addingOnModelCreatingTrue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
